### ISSUE TITLE
docs(contribution-guidelines): add best practices as a subsection

### ISSUE THREAD

**Issue by JeremyFriesenGitHub** [cuhacking/2025#104]
**What feature should we improve? Please describe.**
We need to add a best practices subsection in the coding contribution guidelines. This would showcase new developers / external contributors the best way / practices to contribute code for cuHacking. This also sets a standard for other developers and overall generally documents. Best practices would be focused on creating sections for testing, docs, features, frontend, backend and much more to show case the standard when it comes to making commits in the cuHacking project.  

**Describe the solution you'd like**
- Implement a ``best practices`` subsection to showcase the best way and/or examples of how to contribute for cuHacking. 

**Additional context**
When working with new contributors, we need to be ready with standard guidelines that are well-documented so that they can be properly on-boarded and can contribute meaningfully to cuHacking.

**Comment by AshwinSri23** [comment]
@ryanlyrl @cloverzer0 @MFarabi619 @JowiAoun 
I have currently been given the task to get information on best practices for different areas of cuHacking's infrastructure. If possible, I would like to discuss with each of you the guidelines that you follow as a part of your work. Please reach out to me by replying to this comment.

**Comment by MFarabi619** [comment]
Hey @AshwinSri23, for sure; thanks for taking this on. As we wrap up our scaffolding work, the volume of code we're pumping out is rising pretty fast. Did you want to do this synchronously or asynchronously?

We currently have a [docs site](https://main.dzzy1fby58ukt.amplifyapp.com/docs), which is pretty much always a work-in-progress and serves as our single source of truth for all of our best practices and documented patterns.

**Comment by AshwinSri23** [comment]
I don't mind doing either. If you would like to contact me asynchronously, you can direct message me on discord. My username is ash6843. Alternatively, we could try and schedule a meeting to discuss this matter in further detail. 

Any information that I get from any of you on best practices would be added to the docs site. I have made a draft pull request for this. Here is the link to it: https://github.com/cuhacking/2025/pull/112

**Comment by MFarabi619** [comment]
Sounds good thanks Ashwin, let me get back to you. Hasith should already be in touch.
