### ISSUE TITLE
[BUG]: next button error on docs site

### ISSUE THREAD

**Issue by JeremyFriesenGitHub** [cuhacking/2025#107]
**Describe the bug**
For the docs site, we are having issues/bugs with the buttons for the ``Next`` page (see error description below). 

**To Reproduce**

**Note that this is previous to PR #83, which has a hotfix that solves this temporarily. Make sure to use an older version of the docs to replicate the error.**
1. Go to any index-type page of the docs site (for instance the the tools-overview quick-start page, the contribution-guidelines quick-start page or the knowledge-base quick-start page).
2. Scroll down to the bottom of the page.
3. Click on the ``Next`` button to try and go to the next page. 
4. You will see that for any of these three pages, you will not be able to go to the next page in the section (as you will be constantly looping in the same page that you are on). 

**Expected behavior**
This is not supposed to happen, as we are supposed to provide clear accessibility between the pages, so users can access the next page in any section seamlessly. Going backwards from pages causes no errors (using the ``Previous`` button). 

**Additional context**
To temporarily fix this, I changed the meta json for every section so that the table (on the left-hand side) doesn't recognize distinctively the index page as that quick-start (linked commit is here 57ac3a6a358d234cc3bb6903ea370a9eb0abafe6, please disregard the bad commit type 😭). However, I believe that this is primarily a routing issue. What needs to be done, is that the route likely for that needs to change. so instead of having ``http://localhost:3000/docs/contribution-guidelines``, it would be something like ``http://localhost:3000/docs/contribution-guidelines/quick-start`` or something like that. That way, everything would be ok for the left-hand table, and we could thus link the page nicely.

**Comment by MFarabi619** [comment]
Resolved after migration to Fumadocs 14
