### ISSUE TITLE
chore: initalize shadcn/ui library 

### ISSUE THREAD

**Issue by HasithDeAlwis** [cuhacking/2025#117]
## 🆘 **What is the problem at hand?**
We need a centralized area to put all our UI components in the repo, otherwise, the portal might have one button and our website might have another button, leading to an inconsistent UI and branding across our apps. 

## 🚀 **What is the impact of the problem? How is this problem important? How does it affect users/developers?**
Having the components in one place with a centralized design system is essential for a faster dev experience and consistency among apps.

**Comment by MFarabi619** [comment]
Done in #97
