### ISSUE TITLE
chore(website): connect design system to Remix app

### ISSUE THREAD

**Issue by JeremyFriesenGitHub** [cuhacking/2025#122]
## 🆘 **What is the problem at hand?**

We need to properly setup the remix app to connect to the design system that we currently have established in the figma. This will allow consistency in color schema, and would be smooth to integrate and implement, creating a seamless connection between development and design.

**Comment by HasithDeAlwis** [comment]
@JeremyFriesenGitHub I'm going to close this issue, not really sure what it's about, we can reopen if needed

**Comment by JeremyFriesenGitHub** [comment]
> @JeremyFriesenGitHub I'm going to close this issue, not really sure what it's about, we can reopen if needed

Idk, it was on the figma that u told me to add
