### ISSUE TITLE
Inspiration

### ISSUE THREAD

**Issue by HasithDeAlwis** [cuhacking/2025#13]
## Inspiration

On this issue leave any pictures, screen recordings, or links of other hackathon platforms you liked and think would help CU Hacking.

**Comment by MFarabi619** [comment]
Hack the 6ix Application Portal
![image](https://github.com/user-attachments/assets/f221e0b4-9858-4bca-a028-d443ae525de8)
![image](https://github.com/user-attachments/assets/ba1cc3b6-7447-4fd9-aa28-64aa2ea15cc6)
![image](https://github.com/user-attachments/assets/903b3275-f6d1-4eca-9e4f-a70bbfc2a73d)
![image](https://github.com/user-attachments/assets/1befb500-088a-4167-857a-f6e684d47612)
![image](https://github.com/user-attachments/assets/20a534b3-5d0a-47ba-b5b0-e76a7158ef18)
![image](https://github.com/user-attachments/assets/b03facf8-4e08-4739-89ee-8c0dc1e9343d)

**Comment by HasithDeAlwis** [comment]
See Figjam on [Infrastructure Design](https://www.figma.com/board/ysyvLdc360g77xMrC2238C/Infrastructure-Design?node-id=0-1&t=S4S56fkl4mdJJ2Ti-1)

**Comment by JeremyFriesenGitHub** [comment]
similar to issue #50 would this be closed as well?
