### ISSUE TITLE
docs(known-issues): log common problems and solutions

### ISSUE THREAD

**Issue by MFarabi619** [cuhacking/2025#135]
## 🆘 **What is the problem at hand?**

I often find myself running into the same problems and stumbling upon the same solutions. Not documenting these solutions costs valuable time in the future.

## 🚀 **What is the impact of the problem? How is this problem important? How does it affect users/developers?**

There are a number of problems that pop up consistently and have a definite solution pattern. Document these patterns so that others can save both their time and sanity.

Start with the following:

- Builds for apps fail in CI/CD if playwright isn't installed first. Not sure why, triage further.
- Nx commands will fail after a lib/app is initialized, as it initializes them in .cjs by default. This can be fixed by modifying the ESlint config and the TS config.

**Comment by JeremyFriesenGitHub** [comment]
hello, would migration fix this issue? i've logged a new bug #193, should that have been written in here or should we make just full issues about this?

**Comment by MFarabi619** [comment]
> hello, would migration fix this issue? i've logged a new bug [#193](https://github.com/cuhacking/2025/issues/193), should that have been written in here or should we make just full issues about this?

@JeremyFriesenGitHub Let's talk about it after the meeting this evening
