### ISSUE TITLE
build(website,portal,docs,eslint-config): deploy to netlify

### ISSUE THREAD

**Issue by JowiAoun** [cuhacking/2025#136]
## 🆘 **What is the problem at hand?**

We would like to deploy our apps to Netlify.

## 🚀 **What is the impact of the problem? How is this problem important? How does it affect users/developers?**

Having a working application allows us to easily view main.

**Comment by HasithDeAlwis** [comment]
@JowiAoun please take this on now as a codeowner of this space, we'll discuss timelines Monday
