### ISSUE TITLE
chore: create analytic charts for project management

### ISSUE THREAD

**Issue by HasithDeAlwis** [cuhacking/2025#156]
# What is the problem?
Currently, there is no way for me, or future PMs, to monitor analytics or the dev team to monitor their progress on projects on a larger scale. 

# What is the solution?
Use the GH projects boards chart to monitor the progress on each app (portal, website, and docs) and gain insights into the types of problem we're solving. 

### [What's Done](https://github.com/orgs/cuhacking/projects/4/insights/9)
- Bug chart: To monitor bugs on our apps
- Progress monitoring: See the counts of progress on each app (backlog, todo, in-review, done, etc.)
- Project backlog: See how large the backlog is for each app
- Task distribution: How much each contributor is doing and what type of tasks are they doing

### What to do
- Setup burndown charts
- Velocity charts
- Completion rate (PRs Opened vs Closed)
- Milestone & sprint completion charts 
- Task aging chart (Show how long tasks have been open or stuck in a particular stage (e.g., In Progress or Review)

**Comment by HasithDeAlwis** [comment]
Would appreciate any feedback on these fyi

**Comment by JeremyFriesenGitHub** [comment]
for the charts, i'm curious abt what specific software you are trying to use. Is this a GH project board built-in feature/component?
