### ISSUE TITLE
[Investigation] Investigate creating roles through Next Auth

### ISSUE THREAD

**Issue by HasithDeAlwis** [cuhacking/2025#16]
In Next auth we need a way to create roles (ie. admin and user) to create different view across the platform. Look into how this is done and leave your findings in the comments.

**Comment by AquaShotRyan** [comment]
I made a notion document with everything I found:
https://neighborly-april-104.notion.site/How-to-add-role-based-authentication-in-NextAuth-js-d5e353307a1f4dca9f77fc2abdd07e7f?pvs=4

Let me know if there's any questions.
