### ISSUE TITLE
fix(ui/website): spline animations don't run smoothly

### ISSUE THREAD

**Issue by Aashna-Verma** [cuhacking/2025#182]
### Search checkbox

- [X] Have you searched for similar [issues](https://github.com/cuhacking/2025/issues)?

### Description

The Spline animations need better placement so the text is readable. They also don't run smoothly and need to be updated.

### Steps to reproduce

1. Go to website
2. Scroll

### Actual result

Spline animations are janky

### Expected result

Spline animations should be smooth

### Reproduces how often

Easily reproduced

### Reproducibility

- [X] in Safari?
- [X] in Firefox?
- [X] in Chrome?
- [X] for mobile devices?
- [X] for tablet devices?
- [X] for desktop devices?

**Comment by HasithDeAlwis** [comment]
Closing because we don't work w/Spline anymore.
