### ISSUE TITLE
refactor(docs-e2e): repair failing suite due to broken selectors

### ISSUE THREAD

**Issue by HasithDeAlwis** [cuhacking/2025#184]
### Search checkbox

- [x] Have you searched for similar [issues](https://github.com/cuhacking/2025/issues)?

### Platforms

Docs

## Problem
Docs e2e test suite breaks with after fumadocs v14 migration due to broken selectors

## Solution
- Fix selectors
- Update structure to use `utils` in `libs` folder, following FSD principles

**Comment by cheenoxd** [comment]
Ill be taking this on as well as jeremy if thats alright

**Comment by HasithDeAlwis** [comment]
@JeremyFriesenGitHub you can get the final say on this since it's your area of ownership, whatever happens, this has to be prioritized. Feel free to setup a call if you need guidance @cheenoxd

**Comment by JeremyFriesenGitHub** [comment]
@HasithDeAlwis wip, making pr with him abt this
