### ISSUE TITLE
fix(docs/navbar): Design link broken

### ISSUE THREAD

**Issue by JeremyFriesenGitHub** [cuhacking/2025#197]
### Search checkbox

- [x] Have you searched for similar [issues](https://github.com/cuhacking/2025/issues)?

### Description

Currently in our docs site, the design link doesn't work. We want to be able to have links and everything working accordingly.

### Steps to reproduce

1. Go to the cuHacking page
2. Click on Design link in navbar/header
3. Link/Page does not exist

### Actual result

![Image](https://github.com/user-attachments/assets/0d798b13-a894-4447-b2aa-ff673d7fdea9)

### Expected result

Should take to proper design link..,

### Reproduces how often

Easily reproduced

### Reproducibility

- [x] in Safari?
- [x] in Firefox?
- [x] in Chrome?
- [x] for mobile devices?
- [x] for tablet devices?
- [x] for desktop devices?

**Comment by khizarrm** [comment]
I can take this one.
