### ISSUE TITLE
fix(docs/navbar): ESLint link broken

### ISSUE THREAD

**Issue by JeremyFriesenGitHub** [cuhacking/2025#198]
### Search checkbox

- [x] Have you searched for similar [issues](https://github.com/cuhacking/2025/issues)?

### Description

Currently in our docs site, the ESLint link doesn't work. We want to be able to have links and everything working accordingly.

### Steps to reproduce

1. Go to cuHacking docs site
2. Click on ESLint in Navbar
3. Page does not exist

### Actual result

![Image](https://github.com/user-attachments/assets/1c0c4cb6-5a26-4a26-a83e-b766d2ad899f)

### Expected result

Should take to cuHacking ESLint page like this:

![Image](https://github.com/user-attachments/assets/4c71c609-b932-4763-a5f7-686a0221f976)

### Reproduces how often

Easily reproduced

### Reproducibility

- [x] in Safari?
- [x] in Firefox?
- [x] in Chrome?
- [x] for mobile devices?
- [x] for tablet devices?
- [x] for desktop devices?

**Comment by khizarrm** [comment]
I can take this one.
