### ISSUE TITLE
docs(tech-stack): fix broken shadcn link

### ISSUE THREAD

**Issue by khizarrm** [cuhacking/2025#200]
### Search checkbox

- [x] Have you searched for similar [issues](https://github.com/cuhacking/2025/issues)?

### Platforms

docs

### Description

Shadcn link redirect was going to an url which did not exist. 

## Screenshots (if applicable)

| Current           | Intended            |
| ------------------ | ----------------- |
| <img width="841" alt="Image" src="https://github.com/user-attachments/assets/1e5d6421-11be-4fe8-928a-2d5ecd01d543" /> | <img width="1434" alt="Image" src="https://github.com/user-attachments/assets/f85cee6f-31bd-4c0b-88c4-42abba08009e" /> |

**Comment by khizarrm** [comment]
I'd like to work on this.

**Comment by HasithDeAlwis** [comment]
Thanks for taking this on 🙏
