### ISSUE TITLE
[ADR]: Research and Audit DevOps Patterns and Antipatterns

### ISSUE THREAD

**Issue by MFarabi619** [cuhacking/2025#42]
**Problem Statement**

Developing in teams is generally a painful experience due to inconsistent code quality, delayed deployments, and increased risk of errors. Check out this [great resource](https://dzone.com/refcardz/continuous-integration) for strong guiding principles.

**Goals**
1. Establish a strong development rhythm, and aggressively remove blockers.
2. Improve code quality with customized linter configs.
3. Use webhooks to enhance team collaboration and communication.
4. Increase deployment frequency with better pipeline architecture.
5. Set up regular build intervals.
6. Predict requirements and rapidly manage technical debt.
7. Increase testing coverage to increase reliability. 
8. Make a staging environment for defense in depth.
9. Set up logging and monitoring (DevSecOps).
10. Increase security efforts with code scanning tools (DevSecOps).
11. Use Dependabot to keep packages up-to-date (DevSecOps).

**Out of Scope**
- Extensive end-to-end testing for all features.

## Solution Summary

- Failing early, fast, and small.
- Shifting hard left with early testing and security.
- Using isolated triggered build environments.
- Implementing automated scripts and testing.
- Removing development blockers aggressively.

**Other Options Considered**
- No other options considered. No one wants to do this stuff again and again by hand. Use the robots.

**Comment by JeremyFriesenGitHub** [comment]
haven't implemented 😢
