### ISSUE TITLE
[FEAT. IMPROVEMENT] E2E Testing For Mobile on Docs Site

### ISSUE THREAD

**Issue by HasithDeAlwis** [cuhacking/2025#48]
**What feature should we improve? Please describe.**
Currently there is no E2E testing for mobile on our doc site. This is necessary as over [50% of all web traffic is from mobile phone](https://www.statista.com/statistics/277125/share-of-website-traffic-coming-from-mobile-devices/#:~:text=Mobile%20accounts%20for%20approximately%20half,percent%20of%20global%20website%20traffic.).

**Describe the solution you'd like**
Use playwright and modify the files to add mobile testing on our docs site. 

**Describe alternatives you've considered**
None. We need testing for mobile. 

**Additional context**
N/A

**Comment by MFarabi619** [comment]
@HasithDeAlwis This isn't a feature, it's test
