### ISSUE TITLE
[ADR]: deploy Other Hackathon Projects as Part of Market Research

### ISSUE THREAD

**Issue by HasithDeAlwis** [cuhacking/2025#50]
**Problem Statement**
Building a hackathon site is a solved problem. It's been done by several universities, and we don't need to reinvent the wheel. We just need to optimize it. 

Sites to clone: 
[mcHacks](https://github.com/hackmcgill)
[HackThe6ix](https://github.com/hack-the-6ix)
[TESC](https://github.com/UCSDTESC/Check-in`)
- This is a check-in platform

[Awesome Hacks](https://github.com/dribdat/awesome-hackathon?tab=readme-ov-file)
- List of hackathon management tools we can be inspired from

**Resource**
[Carol Chu HtN](https://www.carolchu.ca/hacker-apps-2020)

**Goals**
Goal 1: Cone the repositories
Goal 2: Deploy on Vercel or Netlify
Goal 3: If you are unable to deploy for whatever reason, screen record yourself

**Out of Scope**
N/A

## Solution Summary
**History/Context**
Hackathons platforms and management systems for hackathons are a solved problem, we don't need to waste time building features that aren't needed or sub-optimally designing something. 

**Solution**
Clone all the repos and deploy them. 
Use these sites as inspiration for how we'll design and implement new features for our site. 

**Other options considered**
N/A

**Note**
This should be done incrementally, this provides valuable insight. Once deployed comment down here.

**Comment by HasithDeAlwis** [comment]
mcHacks App Link: https://hasith-mchacks.netlify.app/
Message me to get admin privileges on the app 👍

**Comment by JeremyFriesenGitHub** [comment]
would this be closed since we did mchacks and hth?

**Comment by JeremyFriesenGitHub** [comment]
closed, we did this alr
