### ISSUE TITLE
docs: add auth flow to docs site

### ISSUE THREAD

**Issue by HasithDeAlwis** [cuhacking/2025#51]
**What feature should we improve? Please describe.**
The doc site is number number 1. It is our source of truth. It is where we can document everything. To minimize context switching for devs, let's move documentation that is on GitHub or Notion to our docs site. 
For now we have the following to move:
- Next Auth Flow
- @ryangchung's authorization role flow
- ~~Google Calendar to docs site~~ (moved to another issue)

**Describe the solution you'd like**
Going forward, we can easily transcribe something from GitHub to the Doc's site since they all use MDX. For the future, we want to automate the process of having documentation on GitHub Issues or discussions also on our docs site. 

**Describe alternatives you've considered**
Keeping everything on Notion is not viable, it's not ideal for devs to have to switch back and forth from notion and go searching for a piece of technical documentation, on the docs site its easy for all. 
Having all documentation on GitHub is a viable strategy, but the only problem is, it might get lost and hard to find among all the issues we write.

**Comment by MFarabi619** [comment]
If possible, please look into rendering the google calendar themeable with the theme toggler. Light mode is an accessibility issue for me.

**Comment by AquaShotRyan** [comment]
Since the custom sign-in page was never pushed to main and roles are not added yet, should I only document what we have so far?

**Comment by HasithDeAlwis** [comment]
In my opinion it would be valuable to still have that. We are going to need it eventually so its good to get that on the docs site now, so that anyone can access it easily when we start developing features.

**Comment by AquaShotRyan** [comment]
**I made an outline and was wondering if I was missing anything:**
- Setup (from hastith’s next auth flow document)
    - prisma setup
    - auth options
        - maybe also explain JWT?
        - explain the pages {}?
        - add in the comments we have in the code into the doc as well?
    - providers
        - how to add providers
    - wrapping components around a <SessionProvider>
        - explain what this does and how to do it
- Login flow (from hasith document and my signin-page branch)
    - adding a custom sign in page
    - signIn() and signOut()
- Role based authentication (stuff from the document I created)

After completing the full version, should I make a markdown version or go straight to making an mdx on another branch? Also, we need to make a category to put this in as I don't think it fits into any of the current ones.

**Comment by HasithDeAlwis** [comment]
This looks good, I'd recommend making it in MDX right away. Have separate documents for Setup, Login, and Role based auth. You can add it under Knowledge Base imo, if we need to change it, it'd be very simple to do so. Feel free to make a draft PR if you're having trouble on anything, and we can give you support 👍

**Comment by AquaShotRyan** [comment]
@MFarabi619 thoughts on using [this](https://github.com/ericz1803/react-google-calendar) to embed google calendar? We can't dark theme the one Google provides.

**Comment by MFarabi619** [comment]
@AquaShotRyan Looks sick, go for it. I better be blown away by your React-foo.

**Comment by MFarabi619** [comment]
Look into [react-calendar](https://github.com/wojtekmaj/react-calendar) as well to see if events from multiple calendars can be pulled.

**Comment by HasithDeAlwis** [comment]
> @HasithDeAlwis in your document about NextAuth, you have a section at the end on how to protect endpoints and pages (use getServerSideProps() for a page and TRPC for middleware). Should I use what you wrote or what I wrote (only NextAuth) in my role-based authentication document? I could include both, or leave it blank for when we decide on which one to use.

You can add both, I think it shows good transparency to show what two ideas we were thinking 👍 
Good work on this so far 👍 :rocket:

**Comment by AquaShotRyan** [comment]
What exactly do we want the calendar to look like and do? It seems harder to integrate google calendar with react-calendar.

**Comment by HasithDeAlwis** [comment]
Looks wise, I think your first example you showed was spot on, at least for me. If react-calendar doesn't work as well with google calendar, that's fine. Maybe write a short comment down here explaining why (this is a good record & it's good practice for writing down documentation), and justify why react-google-calendar was the right move.

**Comment by MFarabi619** [comment]
Yeah it's up to you whichever one you want to use. If you document the pros, cons, and tradeoffs then everyone on the can learn from it and avoid similar pitfalls as Hasith mentioned.

The challenge we're trying to address is that right now I have to context switch to another tab or window to see the meeting schedule for dev. It would be valuable to be able to see it just within the docs site. It'll also help plan our projects better.

An example of helping minimize context switching or providing a quick tunnel is this:

![image](https://github.com/user-attachments/assets/6660b82a-9ce7-4bc8-8d0f-aead00c7570f)

and this:

![image](https://github.com/user-attachments/assets/58923179-b649-4f6a-9e68-f15de4573af3)

It's up to you want you want it to look like. Right now I'm imagining something like this (dark mode-first):

![image](https://github.com/user-attachments/assets/bc242bdd-01e9-4778-a22c-b5fa4765a6d7)

You can extend this with a toggle so that the user can see meetings just for the current week, next week, next/previous month, etc. 

As a user it would be valuable to be able to click on the event and add it to my google calendar. It would also be huge if I could click on it and see where it's happening, and also the meeting minutes doc.

**Comment by MFarabi619** [comment]
@HasithDeAlwis @AquaShotRyan Moving the docs over from Notion, and adding a google calendar are two separate concerns. This should be split up into two different issues.

**Comment by AquaShotRyan** [comment]
Should I make a pull request only for adding to the auth flow to the docs? If so, what keyword should I use to link the PR to this issue?

**Comment by MFarabi619** [comment]
It's up to you. You can re-name this issue to one or the other and then make the corresponding PR. What I do right now is make a branch from here:
| | |
|-|-|
|  ![image](https://github.com/user-attachments/assets/61673bad-6544-4c5f-9a86-7b0e76cb57d9) |  ![image](https://github.com/user-attachments/assets/01027eba-ff52-4696-9e96-90b3030fe185) |

And then on my [PR](https://github.com/cuhacking/hackathon/pull/60) do the following:

![image](https://github.com/user-attachments/assets/2e31f5bc-7194-461a-8f62-58a737ae2476)

I haven't looked into keywords but we should start using them. I'm assuming you mean the the hash in parantheses like these:

![image](https://github.com/user-attachments/assets/cde7f48e-b31b-46b2-9e3e-ff5a22817a8b)

And [these](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)

![image](https://github.com/user-attachments/assets/af75134e-420d-49fb-be54-68aefba2dfa2)

 Feel free to let us know how the system works and how we should use it, I'd love to learn.
