### ISSUE TITLE
chore(issue-templates/pr-templates):  add content to improve clarity

### ISSUE THREAD

**Issue by HasithDeAlwis** [cuhacking/2025#77]
**Problem Statement:**
---
Currently, there isn't a great way to write issues and PRs to convey certain tasks that we have and it's causing decision fatigue. There are also times when certain rules and guidelines aren't followed in PRs. 

**Goals:**
---
1. Create an issue templates for the following
     - docs
     - testing
2. Create PR templates for the following
    - features
    - ADRs
    - tests
    - docs
3. Include a PR checklist for each PR

**Solution**
---
With specific issues along with a PR checklist they can serve as guidelines for how to make higher quality issues and PRs.

**Comment by JeremyFriesenGitHub** [comment]
is this the same as issue #78? if so this should be just one issue then...

**Comment by MFarabi619** [comment]
> is this the same as issue #78? if so this should be just one issue then...

Yes you can close the other one
