### ISSUE TITLE
docs(contribution-guidelines): add github issue writing conventions

### ISSUE THREAD

**Issue by HasithDeAlwis** [cuhacking/2025#78]
Problem Statement
---
There have been several issues that could be named better. This has the potential to impact our server bot and cause version bumps for our docs site. 

Goals
---
1. Clearly layout how to name an issue so that no more confusion spreads
2. Guide the user on what template to use

Solution Summary
---
With clear steps and a guidelines, it will minimize confusion among the team and external contributors.

**Comment by JeremyFriesenGitHub** [comment]
is this going to be the same thing as pr contribution-guidelines? or would a seperate issue be necessary...
